# 使用前请重命名为 docker-compose.yml
version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: server/Dockerfile
    depends_on:
      - neo4j
      - qdrant
    environment:
      - NEO4J_HOST=neo4j
      - NEO4J_PORT=7687
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    volumes:
      - ..:/app
    networks:
      - moremem-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - moremem-network
    environment:
      - NGINX_HOST=moremem.xyz
      - NGINX_PORT=443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

  # 初始化证书
  certbot-init:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    command: >
      certonly --webroot
      --webroot-path /var/www/certbot
      --email 2404385626@qq.com
      --agree-tos
      --no-eff-email
      -d moremem.xyz
      -d www.moremem.xyz

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/mo123456789
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ~/volume/neo4j/data:/data
      - ~/volume/neo4j/logs:/logs
      - ~/volume/neo4j/conf:/var/lib/neo4j/conf
      - ~/volume/neo4j/import:/var/lib/neo4j/import
      - ~/volume/neo4j/plugins:/var/lib/neo4j/plugins
    networks:
      - moremem-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC
    volumes:
      - ~/volume/qdrant:/qdrant/storage:z
    networks:
      - moremem-network

networks:
  moremem-network:
    driver: bridge